# Find more information on toml format here:?  https://github.com/toml-lang/toml???
modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
modId="subterranean" #mandatory
logoFile=""
version="${version}" #mandatory
displayName="Subterranean" #mandatory
displayURL="..."
authors="TelepathicGrunt"
credits="special thanks to all the Forge tutorials and debugging help from other modders to help make this mod possible!"
# The description text for the mod (multi line!) (#mandatory)
description='''An ember in the dark... light the way, into the deep...'''